const MENTORS = [
{
   "Timestamp":"9/16/2016 16:29:38",
   "Name":"Adam K Jensen",
   "Location":"Seattle, WA",
   "JobTitle":"Front End Engineer",
   "Employer":"",
   "Background":"1508 Alumni. Worked at various startups doing customer relations. I started coding out of curiosity which led me to helping customers with their Wordpress blogs. Now I work with Modern Javascript, JS frameworks ( primarily React ), babel , Webpack, etc. Lots of Front-End stuffs. I currently live in Seattle, WA. I can possibly provide insight on the following topics: Front End tooling and languages, Remote work,  resume prep, job searching, networking remotely(not in Denver).",
   "Technical":"Ruby/Rails, CS Fundamentals, Technical Interview Prep, node.js, React.js, Civic Tech, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"@adamki",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 16:58:53",
   "Name":"Adrienne Domingus",
   "Location":"Seattle, WA",
   "JobTitle":"Software Engineer",
   "Employer":"Skilljar",
   "Background":"Alum",
   "Technical":"Ruby/Rails, Python/Django",
   "NonTechnical":"Wellness & Stress Management",
   "Preferred":"Slack",
   "Slack":"@adrienne",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"2/15/2017 11:30:37",
   "Name":"Al Scott",
   "Location":"Denver, CO",
   "JobTitle":"Lead Developer",
   "Employer":"Campspot",
   "Background":"Software developer with lots of experience with startups and consulting.",
   "Technical":"Ruby/Rails, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, Angular, Ember, UI Development (Mockup --> Markup), CSS/Sass, Java, Testing, TDD, Architecture",
   "NonTechnical":"Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack",
   "Slack":"@al.scott",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime"
},
{
   "Timestamp":"9/16/2016 14:15:09",
   "Name":"Alex Jensen",
   "Location":"Colorado",
   "JobTitle":"Developer",
   "Employer":"DRH Internet",
   "Background":"alumni",
   "Technical":"Ruby/Rails, Functional Programming, CS Fundamentals, React.js, elixir",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"@alexj",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"always open for questions. no particular schedule for pairing"
},
{
   "Timestamp":"9/17/2016 8:48:06",
   "Name":"Andrew Thal",
   "Location":"Brooklyn, New York",
   "JobTitle":"Engineer IV",
   "Employer":"2U",
   "Background":"Hungry Academy Alumnus, previously wrote software at LivingSocial and Bonobos. Turing mentor for ~2 years",
   "Technical":"Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js, CSS/Sass, Python, Elixir",
   "NonTechnical":"Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack or Email",
   "Slack":"@athal7",
   "Email":"hello@athal7.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime"
},
{
   "Timestamp":"9/22/2016 23:42:22",
   "Name":"Andy Mention",
   "Location":"Leadville, CO",
   "JobTitle":"Software Engineer",
   "Employer":"Wellmatch (or something)",
   "Background":"1406 4 lyfe, also all the CO sporty things",
   "Technical":"Ruby/Rails, DevOps, Functional Programming",
   "NonTechnical":"Wellness & Stress Management",
   "Preferred":"Slack or Email",
   "Slack":"@andydangerous",
   "Email":"amention@gmail.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts, vim/tmux :)",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"12/2/2016 12:41:15",
   "Name":"Angela Lindow",
   "Location":"Denver, CO",
   "JobTitle":"Software Engineer",
   "Employer":"P2Binvestor",
   "Background":"Alumna, Parent, Previously worked for this company in an operations role, English major",
   "Technical":"Ruby/Rails, CSS/Sass",
   "NonTechnical":"Resume & Cover Letters, Culture/Behavioral Interview Prep, Parenting",
   "Preferred":"Slack",
   "Slack":"@angela",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Available for questions via slack throughout the day"
},
{
   "Timestamp":"10/5/2016 16:21:25",
   "Name":"Bradley",
   "Location":"Sheehan",
   "JobTitle":"",
   "Employer":"Advanced Energy Economy",
   "Background":"gSchool[0], married and live in Massachusetts, from Colorado, love drumming, environmental/energy policy advocate",
   "Technical":"Ruby/Rails, React.js, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Wellness & Stress Management, Project Management, Resume & Cover Letters",
   "Preferred":"",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts, Zoom",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 14:20:12",
   "Name":"Brett Grigsby",
   "Location":"Denver, CO",
   "JobTitle":"",
   "Employer":"DagonIT",
   "Background":"Alum in my first job",
   "Technical":"Ruby/Rails, Functional Programming, Angular",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"4/10/2017 13:44:50",
   "Name":"Brett Nekolny",
   "Location":"Denver, CO",
   "JobTitle":"Sr. Manager of Engineering",
   "Employer":"Under Armour Connected Fitness",
   "Background":"Love for leadership and growing people. Eager to fill any role in a group and organization.",
   "Technical":"Python, System Design",
   "NonTechnical":"Project Management, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"SMS",
   "Slack":"",
   "Email":"",
   "Phone":"6302020783",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"9/23/2016 11:24:17",
   "Name":"Brian Winterling",
   "Location":"Denver, CO",
   "JobTitle":"Sr. Software Developer",
   "Employer":"",
   "Background":"Always enjoyed learning new things, which is why my resume is a giant mess.  Mostly technical things like telecom and A/V, but also launched both a product and consulting business.  Then on to Casimir's version of gSchool.  When I'm not hanging out with my two kids, I'm playing tennis, going to a concert or doing something really outdoorsy.",
   "Technical":"Ruby/Rails, React.js, Elixir",
   "NonTechnical":"Project Management, Parenting",
   "Preferred":"Slack or Email",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"10/18/2016 20:53:15",
   "Name":"Brooke Kuhlmann",
   "Location":"Boulder, CO",
   "JobTitle":"Software Developer",
   "Employer":"",
   "Background":"Generally spend my free time on the craft, namely: open source.",
   "Technical":"Ruby/Rails, DevOps, Personal Development/GTD",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"9/20/2016 13:10:54",
   "Name":"Chelsea Johnson",
   "Location":"Broomfield, CO",
   "JobTitle":"Web Developer",
   "Employer":"Points of Light",
   "Background":"speech therapist",
   "Technical":"Ruby/Rails, node.js, Ember, Civic Tech",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"@cheljoh",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"9/17/2016 21:13:38",
   "Name":"Chris Cenatiempo",
   "Location":"Kailua, HI",
   "JobTitle":"Software Engineer",
   "Employer":"RealGeeks",
   "Background":"1507 Alumni, and former Electrical Engineer/Musician",
   "Technical":"Ruby/Rails, node.js, React.js, General Problem Solving",
   "NonTechnical":"Project Management",
   "Preferred":"Slack",
   "Slack":"@chrisdinnertime",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, PM"
},
{
   "Timestamp":"9/29/2016 13:30:53",
   "Name":"Chris Downard",
   "Location":"Denver, CO",
   "JobTitle":"Engineering Manager",
   "Employer":"Granicus",
   "Background":"I love helping folks who are learning as I received a ton of help.",
   "Technical":"Ruby/Rails, CS Fundamentals, Technical Interview Prep, React.js, Civic Tech, UI Development (Mockup --> Markup), CSS/Sass, Actual Javascript (tm), Soft skills, management, SDLC, Agile",
   "NonTechnical":"Public Speaking, CFPs, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting, Social Issues in the Tech Industry",
   "Preferred":"",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts, Slack, whatever works",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 15:58:42",
   "Name":"Christopher Moeller",
   "Location":"Milwaukee, WI",
   "JobTitle":"Software Developer",
   "Employer":"Chargify",
   "Background":"Self taught developer focused on Ruby on Rails and JS (mostly React at work)",
   "Technical":"Ruby/Rails, Functional Programming, React.js",
   "NonTechnical":"Wellness & Stress Management, Project Management",
   "Preferred":"Slack (if urgent) else Email",
   "Slack":"@cmoel",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Some weekends at various times"
},
{
   "Timestamp":"9/16/2016 20:19:18",
   "Name":"Danny Glunz",
   "Location":"Denver",
   "JobTitle":"Software Engineer",
   "Employer":"Pana",
   "Background":"1409 alumni - double leo",
   "Technical":"Ruby/Rails, Go, CS Fundamentals, node.js",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"@dglunz",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing",
   "Availability":"Weekends, AM"
},
{
   "Timestamp":"10/7/2016 1:02:10",
   "Name":"Dave Maurer",
   "Location":"Aurora Colorado",
   "JobTitle":"Unemployed",
   "Employer":"",
   "Background":"Alumni",
   "Technical":"Ruby/Rails, Javascript",
   "NonTechnical":"Resume & Cover Letters, Culture/Behavioral Interview Prep",
   "Preferred":"",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing",
   "Availability":"Weekdays, AM, Weekdays, after 5PM, Some weekends. Subject to me not having plans :)."
},
{
   "Timestamp":"9/22/2016 9:10:44",
   "Name":"David Whitaker",
   "Location":"Denver",
   "JobTitle":"Web Developer",
   "Employer":"Points of Light",
   "Background":"Americorps alum, worked in organic/natural food industry prior to becoming a web dev.",
   "Technical":"Ruby/Rails, DevOps, React.js, Ember, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Wellness & Stress Management, Project Management, Resume & Cover Letters",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime"
},
{
   "Timestamp":"9/17/2016 17:59:25",
   "Name":"Emily Freeman",
   "Location":"Denver, Colorado",
   "JobTitle":"Software Engineer",
   "Employer":"Wazee Digital",
   "Background":"I'm a Turing alumni (1508 BE) and graduated in March 2016. I have a 20-month old daughter, Clara, who is the light of my world and served as my inspiration to get through Turing. I'm originally from DC (with an 8-year layover in Florida) and am SUPER passionate about fitness — specifically powerlifting. Previously I worked in PR/Communications and as a ghostwriter. I also briefly worked in politics and non-profit fundraising. I blog when I can at emilydowdle.com.",
   "Technical":"Ruby/Rails, Java",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management, Culture/Behavioral Interview Prep, Parenting, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"@emilyfreeman",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Grabbing lunch, coffee",
   "Availability":"Weekdays,  Lunchtime"
},
{
   "Timestamp":"10/18/2016 21:13:39",
   "Name":"Emily Morehouse",
   "Location":"Denver",
   "JobTitle":"Co-Founder/CTO",
   "Employer":"Cuttlesoft",
   "Background":"Studied Theatre, Criminology and Computer Science (and a little math and psychology for good measure). Avid OSS and CPython supporter/contributor. Recently moved to Denver, still settling my love affair with the mountains and acclimating to living above sea level. Yogi, dog lover, builder, thinker, coffee-drinker, face-maker.",
   "Technical":"DevOps, CS Fundamentals, Technical Interview Prep, node.js, Angular, UI Development (Mockup --> Markup), CSS/Sass, Python/Flask, Ionic",
   "NonTechnical":"Project Management, Resume & Cover Letters, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"@emilym",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"9/17/2016 2:56:01",
   "Name":"Eoin Coffey",
   "Location":"Boulder, CO",
   "JobTitle":"Software engineer",
   "Employer":"Twitter",
   "Background":"A lot of work in backend systems and data flow architecture. Been with Twitter for 4 years via the Gnip acquisition. No bird watching :(",
   "Technical":"Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, Technical Interview Prep, Jvm/scala, \"streaming\" systems",
   "NonTechnical":"Public Speaking, CFPs, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Email",
   "Slack":"",
   "Email":"ecoffey@gmail.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts, Email with some in person at Turing",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"9/18/2016 16:22:07",
   "Name":"Ernie Miller",
   "Location":"Louisville, KY",
   "JobTitle":"Engineering Manager",
   "Employer":"CareZone",
   "Background":"Friend of Turing, occasional visitor (IT HAS BEEN TOO LONG), potential mentor.",
   "Technical":"Ruby/Rails, Technical Interview Prep, React.js, Option 15",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management, Technical Interview Prep",
   "Preferred":"Slack, Email or SMS",
   "Slack":"@ernie",
   "Email":"ernie@ernie.io",
   "Phone":"5027243082",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"3/21/2017 12:43:48",
   "Name":"Frank Valcarcel",
   "Location":"Denver",
   "JobTitle":"CEO",
   "Employer":"Cuttlesoft",
   "Background":"",
   "Technical":"DevOps, Go, CS Fundamentals, Technical Interview Prep, node.js, Angular, UI Development (Mockup --> Markup), CSS/Sass, Python",
   "NonTechnical":"Public Speaking, Speaking proposals, Project Management, Culture/Behavioral Interview Prep, Technical Interview Prep, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"@frank",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts, places with good beer",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"9/17/2016 18:33:26",
   "Name":"Glen Egbert",
   "Location":"Salida, CO",
   "JobTitle":"Developer",
   "Employer":"HubTran",
   "Background":"Alumni, Parent of 2, Working 100% remotely as a dev at HubTran since 2/2015",
   "Technical":"Ruby/Rails, React.js",
   "NonTechnical":"Parenting",
   "Preferred":"Email",
   "Slack":"",
   "Email":"glenegbert1@gmail.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"3/19/2017 18:40:13",
   "Name":"Gurusundesh Khalsa",
   "Location":"Chicago, IL",
   "JobTitle":"Software Engineer",
   "Employer":"Allstate",
   "Background":"Alumni. Very odd mix of things.",
   "Technical":"Ruby/Rails, CS Fundamentals, React.js, Java",
   "NonTechnical":"Technical Interview Prep",
   "Preferred":"Slack",
   "Slack":"@gurusundesh",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"1/30/2017 18:11:32",
   "Name":"Heidi Hoopes",
   "Location":"Denver/Thorton",
   "JobTitle":"Application Developer",
   "Employer":"Aetna",
   "Background":"I'm an alumni who spent time after graduation providing student support at Turing. I'm a parent and formerly was employed as a biologist & tech journalist. I currently work purely on the backend of a Rails/Elixir app that has a different architecture than what you'll experience at Turing.",
   "Technical":"Ruby/Rails, Functional Programming, Elixir",
   "NonTechnical":"Technical Interview Prep, Parenting",
   "Preferred":"Slack or Email",
   "Slack":"@heidi",
   "Email":"heidih@gmail.com",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"2/8/2017 12:11:14",
   "Name":"Horace Williams",
   "Location":"Los Angeles",
   "JobTitle":"Software Engineer",
   "Employer":"Factual",
   "Background":"Former Instructor",
   "Technical":"Ruby/Rails, DevOps, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js, Civic Tech, Python, Clojure",
   "NonTechnical":"Technical Interview Prep, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"@horace",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, PM"
},
{
   "Timestamp":"10/4/2016 15:27:39",
   "Name":"Horacio Chavez",
   "Location":"Monterrey, Mexico",
   "JobTitle":"Founder",
   "Employer":"All & Simple",
   "Background":"1406 Alumni",
   "Technical":"Ruby/Rails, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Project Management, Parenting",
   "Preferred":"Slack",
   "Slack":"@horacio",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts, Code Review via Github's PR",
   "Availability":"Weekdays, after 7PM"
},
{
   "Timestamp":"9/16/2016 14:13:35",
   "Name":"Ian Douglas",
   "Location":"Boulder, CO",
   "JobTitle":"Growth Hacker/DevRel",
   "Employer":"GetStream.io",
   "Background":"20yr webdev experience, love to help with the career side of things like resume feedback and tech interview practice, or working through architecture problems and API development.",
   "Technical":"DevOps, Go, CS Fundamentals, Technical Interview Prep",
   "NonTechnical":"Public Speaking, CFPs, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting",
   "Preferred":"Slack or Email",
   "Slack":"@iandouglas",
   "Email":"ian.douglas@iandouglas.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"9/16/2016 23:22:39",
   "Name":"Jack Yeh",
   "Location":"Denver, CO",
   "JobTitle":"",
   "Employer":"Welltok, Inc.,",
   "Background":"Alumni 1507",
   "Technical":"Ruby/Rails, React.js",
   "NonTechnical":"Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep",
   "Preferred":"Slack",
   "Slack":"@jackyeh",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"10/5/2016 21:17:23",
   "Name":"Jason Pilz",
   "Location":"Anacortes, WA",
   "JobTitle":"Software Developer",
   "Employer":"Rumblefish",
   "Background":"1508 Alum, 3 daughters, work remote, love what I do",
   "Technical":"Ruby/Rails, DevOps",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"@jasonpilz",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"9/16/2016 14:30:02",
   "Name":"Jonah Moses",
   "Location":"Portland",
   "JobTitle":"Software Engineer",
   "Employer":"New Relic",
   "Background":"Alumni (gSchool[1]), Parent, Adventure Sports/Outdoors,",
   "Technical":"Ruby/Rails, React.js",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Parenting",
   "Preferred":"Slack",
   "Slack":"@jonah",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"9/27/2016 11:13:09",
   "Name":"Josh",
   "Location":"Ashton",
   "JobTitle":"Sr. Director",
   "Employer":"Talent @ SendGrid",
   "Background":"HR professional",
   "Technical":"",
   "NonTechnical":"Resume & Cover Letters, Culture/Behavioral Interview Prep",
   "Preferred":"Email",
   "Slack":"",
   "Email":"josh@sendgrid.com",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing",
   "Availability":"Weekdays, AM"
},
{
   "Timestamp":"12/8/2016 17:48:44",
   "Name":"Josh Cass",
   "Location":"Lakewood, CO",
   "JobTitle":"Software Engineer",
   "Employer":"Bonusly",
   "Background":"Alumni on my second job after Turing and soon-to-be parent",
   "Technical":"Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, CSS/Sass",
   "NonTechnical":"Project Management",
   "Preferred":"Slack or Email",
   "Slack":"@joshcass",
   "Email":"hello@joshcass.com",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"3/17/2017 13:52:28",
   "Name":"Josh Washke",
   "Location":"Littleton",
   "JobTitle":"Software Engineer",
   "Employer":"Consova Corporation",
   "Background":"1602 Alumni, former comp sci student. .Net and Angular 2 dev who develops desktop and web application in a windows environment",
   "Technical":"CS Fundamentals, Angular, C#, .Net, SQL",
   "NonTechnical":"",
   "Preferred":"Slack, Email or SMS",
   "Slack":"@jwashke",
   "Email":"jwashke@gmail.com",
   "Phone":"9099106885",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"10/22/2016 10:33:20",
   "Name":"Juan",
   "Location":"Medellín, Colombia",
   "JobTitle":"Full stack developer",
   "Employer":"SpanishDict.com",
   "Background":"I got into programming through getting interested in computational linguistics. The first company I worked for had a training program similar to a bootcamp, so I love chatting with people going through a journey similar to the one I went through when I started",
   "Technical":"DevOps, Functional Programming, node.js, Angular, UI Development (Mockup --> Markup)",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management, Resume & Cover Letters, Technical Interview Prep",
   "Preferred":"Slack",
   "Slack":"@juancaicedo",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"10/10/2016 23:17:16",
   "Name":"July Tran",
   "Location":"Denver, CO",
   "JobTitle":"GIS Developer",
   "Employer":"NREL",
   "Background":"1511 Alumni, background in public health and environmental policy",
   "Technical":"Ruby/Rails, node.js, Ember, Civic Tech, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management, Project Management, Resume & Cover Letters, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"@july",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 14:58:55",
   "Name":"Justin Crawford",
   "Location":"Boulder",
   "JobTitle":"Product Engineer",
   "Employer":"Mozilla",
   "Background":"Cofounder, dojo4. People/project/product manager. Parent.",
   "Technical":"node.js, UI Development (Mockup --> Markup), Option 15, CSS/Sass",
   "NonTechnical":"Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Parenting, Product development. Open source contribution. Marketing. Software process. Agency vs. Product Company vs. In-house jobs.",
   "Preferred":"Slack",
   "Slack":"@hoosteeno",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime"
},
{
   "Timestamp":"9/16/2016 15:04:37",
   "Name":"Kaitlin Barrer",
   "Location":"Denver",
   "JobTitle":"Software Engineer",
   "Employer":"CA Technologies",
   "Background":"I went to Davinci Coders, then worked for a startup, now work for CA.",
   "Technical":"Ruby/Rails, Technical Interview Prep, React.js, Civic Tech, clojure",
   "NonTechnical":"Resume & Cover Letters, Technical Interview Prep",
   "Preferred":"Slack or Email",
   "Slack":"@kaitlinb",
   "Email":"kaitlin.barrer@gmail.com",
   "Phone":"",
   "PreferredLocation":"In Person at Turing",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 18:12:13",
   "Name":"Kurt Harriger",
   "Location":"Denver, CO",
   "JobTitle":"",
   "Employer":"CA Technologies",
   "Background":"Introduced to Turning via a co-worker and alumni Lovisa.  I have 20ish years experience.  I started programming in my teenage years.  I've worked with consulting firms, enterprises and startups.  I'm curious and passionate and always learning -- even now.",
   "Technical":"DevOps, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js",
   "NonTechnical":"Public Speaking, CFPs, Project Management, Resume & Cover Letters, Technical Interview Prep, Parenting",
   "Preferred":"Slack",
   "Slack":"@kurtharriger",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing",
   "Availability":"Weekdays,  Lunchtime, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"10/23/2016 17:18:00",
   "Name":"Lorena Mesa",
   "Location":"Chicago",
   "JobTitle":"Data Engineer",
   "Employer":"Sprout Social",
   "Background":"Friend of the community! Happy to mentor and chat about my transition into tech as I went through the process the past few years from applied social science research to programming.",
   "Technical":"Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, Civic Tech",
   "NonTechnical":"Public Speaking, CFPs, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Email",
   "Slack":"",
   "Email":"me@lorenamesa.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekends, AM"
},
{
   "Timestamp":"9/29/2016 12:10:53",
   "Name":"Lydia Shafer",
   "Location":"Denver",
   "JobTitle":"software developer",
   "Employer":"Wombat Security Technologies",
   "Background":"Alumni",
   "Technical":"Ruby/Rails, Ember, CSS/Sass",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"any",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"9/21/2016 14:02:11",
   "Name":"Marc Chung",
   "Location":"San Francisco",
   "JobTitle":"Senior Software Engineer",
   "Employer":"",
   "Background":"Previously at Lookout and ManCrates. Currently working at Handshake, a recruiting platform for University students.",
   "Technical":"Ruby/Rails, DevOps, Technical Interview Prep",
   "NonTechnical":"Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting, Social Issues in the Tech Industry",
   "Preferred":"",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekdays, after 5PM PST"
},
{
   "Timestamp":"3/30/2017 13:07:27",
   "Name":"Marina corona",
   "Location":"Denver",
   "JobTitle":"Software engineer",
   "Employer":"",
   "Background":"TFA alum, former educator, worked at CaptainU, love skiing. Backend rails developer",
   "Technical":"Ruby/Rails, Technical Interview Prep",
   "NonTechnical":"Public Speaking, Speaking proposals, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack",
   "Slack":"@marinacor",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"11/22/2016 20:49:33",
   "Name":"Mark Miranda",
   "Location":"Denver, CO",
   "JobTitle":"Software Developer",
   "Employer":"The Flyfisher Group",
   "Background":"Alumni!",
   "Technical":"Ruby/Rails, Functional Programming, React.js, Angular, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Project Management, Culture/Behavioral Interview Prep",
   "Preferred":"Slack",
   "Slack":"@mark",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"10/10/2016 13:12:17",
   "Name":"Marlo Major",
   "Location":"Dallas",
   "JobTitle":"",
   "Employer":"",
   "Background":"Alumni. Formerly at Active Network as Ruby dev. Scala enthusiast. JS not really my thing.",
   "Technical":"Ruby/Rails, Functional Programming, CS Fundamentals, Scala",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"@marlomajor",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"9/16/2016 15:01:45",
   "Name":"Matt Ewell",
   "Location":"Salt Lake City, UT",
   "JobTitle":"RoR Developer",
   "Employer":"iCentris",
   "Background":"1507 Alumni, 15+ years in IT as systems engineer, solution architect, etc. before turning dev. Oh I went back to school and graduated with a CS degree in 2013. I enjoy bikram yoga, hiking and skiing.",
   "Technical":"Ruby/Rails, CS Fundamentals, Technical Interview Prep, Civic Tech",
   "NonTechnical":"Wellness & Stress Management, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack or Email",
   "Slack":"@plato721",
   "Email":"matt.ewell@gmail.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"3/28/2017 12:53:46",
   "Name":"Matt Kaufman",
   "Location":"Denver, CO",
   "JobTitle":"Software Developer",
   "Employer":"Concept3D",
   "Background":"1608 Front End Alumni and former industrial robot programmer! I love digging into JS code and helping to solve problems, React is my area of focus/expertise currently. I have a passion for live music and outdoor activities, all the typical Colorado stuff. Just looking to spread the love, is all.",
   "Technical":"CS Fundamentals, Technical Interview Prep, node.js, React.js, Civic Tech",
   "NonTechnical":"Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Jam Bands",
   "Preferred":"Slack",
   "Slack":"@mattk",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 15:01:48",
   "Name":"Matt Rogers",
   "Location":"Dallas, TX",
   "JobTitle":"Sr. Developer",
   "Employer":"Teladoc",
   "Background":"Traditional CS Degree. Dad to two girls.  Have worn the developer, team lead, and manager hats. Mentor since gSchool-1.",
   "Technical":"Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, Technical Interview Prep",
   "NonTechnical":"Wellness & Stress Management, Project Management, Parenting",
   "Preferred":"Slack or Email",
   "Slack":"@mattr",
   "Email":"codemattr@gmail.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"10/8/2016 18:46:03",
   "Name":"Micah Adams",
   "Location":"Denver, CO",
   "JobTitle":"Lead Engineer",
   "Employer":"Homebot",
   "Background":"10 years of professional experience as a full stack/back end engineer.",
   "Technical":"Ruby/Rails, DevOps, Go, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep",
   "NonTechnical":"Public Speaking, CFPs, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack, Email or SMS",
   "Slack":"",
   "Email":"micah.shawn.adams@gmail.com",
   "Phone":"8175077939",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"9/17/2016 7:22:38",
   "Name":"Michael Siegfried",
   "Location":"Santa Barbara, CA",
   "JobTitle":"Senior Engineer",
   "Employer":"Procore Technologies",
   "Background":"Probably birdwatching. I know of Turing through Mimi.",
   "Technical":"Ruby/Rails, DevOps, Technical Interview Prep, Postgres",
   "NonTechnical":"Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack, Email or SMS",
   "Slack":"@siggy",
   "Email":"siggymcfried@gmail.com",
   "Phone":"6616003784",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 14:39:01",
   "Name":"Nathaniel Watts",
   "Location":"San Francisco",
   "JobTitle":"Software Developer",
   "Employer":"InfluxData",
   "Background":"Alumni",
   "Technical":"Go, Functional Programming, React.js",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management",
   "Preferred":"Slack",
   "Slack":"@nathaniel",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"3/17/2017 13:49:07",
   "Name":"Nicholas Dorans",
   "Location":"Fort Collins",
   "JobTitle":"Semantic Technology Developer",
   "Employer":"Semantic Arts",
   "Background":"Turing Alumni 1511, 10 years experience in the HVAC Industry",
   "Technical":"Ruby/Rails, Data Science, CS Fundamentals, node.js, React.js",
   "NonTechnical":"Culture/Behavioral Interview Prep",
   "Preferred":"Slack",
   "Slack":"@nickynonaps",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts, If you're willing to come to Fort Collins, I'll gladly meet with you.",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"1/4/2017 23:26:05",
   "Name":"Noelle Knight",
   "Location":"Washington, DC",
   "JobTitle":"Web Developer",
   "Employer":"Lukens Company",
   "Background":"Female dev, yogi, mom, sister of an alum",
   "Technical":"Angular, UI Development (Mockup --> Markup), CSS/Sass, Javascript, jQuery",
   "NonTechnical":"Wellness & Stress Management, Project Management, Resume & Cover Letters, Parenting",
   "Preferred":"Slack or Email",
   "Slack":"",
   "Email":"noelle.knight@gmail.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"9/16/2016 15:42:09",
   "Name":"Paul Grever",
   "Location":"Denver, CO",
   "JobTitle":"Software Engineer",
   "Employer":"GetOutfitted",
   "Background":"A Turing ALumni 1412. Worked as full stack with meteor, before that was Product Manager for DubLabs building mobile apps for colleges and k-12 schools.",
   "Technical":"Ruby/Rails, node.js, UI Development (Mockup --> Markup), Meteor",
   "NonTechnical":"Project Management",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"3/20/2017 12:32:42",
   "Name":"Peter Carr",
   "Location":"Aspen, CO",
   "JobTitle":"Platform Engineer",
   "Employer":"IBM Compose",
   "Background":"worked in software development for 6 years, received degree in computer science from CU-Boulder",
   "Technical":"Ruby/Rails, Go, Functional Programming, CS Fundamentals",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"@carrpet",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime"
},
{
   "Timestamp":"2/14/2017 15:50:19",
   "Name":"Rich Shea",
   "Location":"Denver",
   "JobTitle":"Software Developer",
   "Employer":"Wombat Security Technologies",
   "Background":"Turing Graduate, Math Teacher, Healthcare Recruiter, Inside Sales for Biotech/Pharmaceutical Industry",
   "Technical":"Ruby/Rails, Ember, JavaScript, Elixir",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime"
},
{
   "Timestamp":"9/22/2016 12:59:56",
   "Name":"Rick Rein",
   "Location":"DC Area",
   "JobTitle":"Senior Software Engineer",
   "Employer":"Akamai",
   "Background":"Started life as a *nix admin, mostly work on getting new products to market, former USMC",
   "Technical":"Ruby/Rails, DevOps",
   "NonTechnical":"Public Speaking, CFPs, Project Management",
   "Preferred":"Slack or Email",
   "Slack":"@rickr",
   "Email":"rick@rudelinux.org",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"9/16/2016 14:20:24",
   "Name":"Robert Cornell",
   "Location":"Denver",
   "JobTitle":"Lead Developer",
   "Employer":"Alkami",
   "Background":`Coding/Professional Background:
1. Alumni-ish of 1502/3/6?
2. 10 years project management experience (architectural lighting control systems / theatrical rigging systems)
3. 3-years software product owner experience with stealth startup in Breckenridge, CO (Cofounder)
4. 8-years Law Enforcement experience (yes I was literally a cop, police car, gun, vest, badge, whole nine-yards) Also directed recruitment and hiring programs as well as lead field training division.
5. < 1 Year, Lead Developer at Alkami (Founder) 6 Clients ranging from healthcare to agriculture industry.
6. I have also run a daycare and have 15 years of experience in musical theatre
Personal Background:
1. Colorado Native (I remember when Colfax was a shithole no one went to)
2. Two kids (17YO Son and 15 YO Daughter)
3. Wife is from Central Asian and I'm learning Russian (She works in financial services in Philadelphia)
4. I travel
5. Love Doctor who (my first Doctor was Tom Baker #4)
6. I'm an introvert and quiet and most people think I'm angry a lot of the time.  (https://www.youtube.com/watch?v=sGlTeRWTsGU and https://www.youtube.com/watch?annotation_id=annotation_732306207&feature=iv&src_vid=sGlTeRWTsGU&v=r99Bznk2QJA)`,
   "Technical":"Ruby/Rails, React.js, I learn quick",
   "NonTechnical":"Wellness & Stress Management, Project Management",
   "Preferred":"Email",
   "Slack":"",
   "Email":"robert@alkami.io",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, As scheduled dependent on my travel schedule"
},
{
   "Timestamp":"9/22/2016 18:12:19",
   "Name":"Robert Gu",
   "Location":"Los Angeles",
   "JobTitle":"Crafter",
   "Employer":"8th Light",
   "Background":"Alum",
   "Technical":"Ruby/Rails, node.js, CSS/Sass",
   "NonTechnical":"Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"1/24/2017 11:41:12",
   "Name":"Robbie Lane",
   "Location":"Denver",
   "JobTitle":"Developer",
   "Employer":"TRELORA",
   "Background":"1508 Alumni",
   "Technical":"Ruby/Rails, node.js, React.js, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Project Management, Culture/Behavioral Interview Prep, Parenting, Social Issues in the Tech Industry",
   "Preferred":"Slack",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM"
},
{
   "Timestamp":"9/16/2016 14:31:34",
   "Name":"Ross Kaffenberger",
   "Location":"Washington, DC",
   "JobTitle":"Senior Software Engineer",
   "Employer":"Freelance",
   "Background":"I just became a dad so now I shovel code and diapers.",
   "Technical":"Ruby/Rails, DevOps, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js, Ember",
   "NonTechnical":"Public Speaking, CFPs, Wellness & Stress Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack or Email",
   "Slack":"@rossta",
   "Email":"osskaff@gmail.com",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, AM, Weekdays, after 5PM"
},
{
   "Timestamp":"9/16/2016 15:11:50",
   "Name":"Ryan Tyer",
   "Location":"Boulder",
   "JobTitle":"Director of Engineering",
   "Employer":"Cloudability",
   "Background":"",
   "Technical":"DevOps, Go, Data Science, Machine Learning, Functional Programming, CS Fundamentals, Technical Interview Prep, node.js, React.js",
   "NonTechnical":"Public Speaking, CFPs, Project Management, Resume & Cover Letters, Culture/Behavioral Interview Prep, Technical Interview Prep, Parenting",
   "Preferred":"Slack or Email",
   "Slack":"@rtyer",
   "Email":"ryan.tyer@gmail.com",
   "Phone":"3037098877",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"12/4/2016 20:09:42",
   "Name":"Sabrina Unrein",
   "Location":"Denver, CO",
   "JobTitle":"Software Developer",
   "Employer":"Gloo",
   "Background":"Graduate of Dev Bootcamp Chicago, working at Gloo since April 2016",
   "Technical":"Ruby/Rails",
   "NonTechnical":"Wellness & Stress Management, Culture/Behavioral Interview Prep, Social Issues in the Tech Industry",
   "Preferred":"Slack or Email",
   "Slack":"@sunrein",
   "Email":"sabrina.unrein@gmail.com",
   "Phone":"",
   "PreferredLocation":"In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"10/13/2016 12:24:17",
   "Name":"Stanley Siudzinski",
   "Location":"Denver",
   "JobTitle":"Software Engineer",
   "Employer":"AT&T",
   "Background":"Alumni, loves long drives on canyon roads in fast cars.",
   "Technical":"Ruby/Rails, React.js, UI Development (Mockup --> Markup), CSS/Sass",
   "NonTechnical":"Wellness & Stress Management, Culture/Behavioral Interview Prep, Brain/Life hacking",
   "Preferred":"Slack or Email",
   "Slack":"",
   "Email":"Stanleyjsdz@gmail.com",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, In Person not at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, AM, Weekends, PM"
},
{
   "Timestamp":"9/27/2016 22:41:48",
   "Name":"Tae Kim",
   "Location":"Iowa",
   "JobTitle":"Javascript Developer",
   "Employer":"Blacklight CMS",
   "Background":`I graduated from Iowa State University with a degree in Software Engineering. I moved out to Denver about 2 1/2 years ago and love it here! This is one of the happiest places in the world.\r\rI had a few jobs back in Iowa. One was very IT-related, one was at a large company developing in Java. Both jobs were ehhhh. When I came to Denver, I joined the consulting community... and boy was it awesome. I learned a ton in my craft, from modern development to managing a team. It was an amazing experience.\r\rNow, I work remotely for a small company called Blacklight CMS. We create and maintain thousands of sites for a niche health market. I'm creating a template engine for them to help automate a lot of that maintenance (think WIX, Squarespace, or Wordpress).\r\rOn the side, I helped start a startup called Zipskee - a social platform to connect locals with travelers. We are a self-driven group of individuals that love what we do.\r\rIn my free time, I love going to shows and playing LoL. For those casuals out there, LoL = League of Legends. I love coding / mentoring on the side, so if you have any questions feel free to ask!`,
   "Technical":"CS Fundamentals, Technical Interview Prep, node.js, React.js, CSS/Sass",
   "NonTechnical":"Culture/Behavioral Interview Prep, Technical Interview Prep",
   "Preferred":"Slack, Email or SMS",
   "Slack":"@taekimjr",
   "Email":"taekimjr@gmail.com",
   "Phone":"5157204901",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, PM"
},
{
   "Timestamp":"10/15/2016 20:49:50",
   "Name":"Thom Schlereth",
   "Location":"Denver CO",
   "JobTitle":"",
   "Employer":"",
   "Background":"Alumni",
   "Technical":"Ruby/Rails, Civic Tech",
   "NonTechnical":"",
   "Preferred":"Slack",
   "Slack":"@thomp",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"5/2/2017 13:25:39",
   "Name":"Tommasina Miller",
   "Location":"Denver",
   "JobTitle":"Software Engineer",
   "Employer":"Granicus",
   "Background":"1605 alumna (last backend-only cohort); Pahlka for life!; you can often find me at Code for Denver; I love community and grass-roots activism",
   "Technical":"Ruby/Rails, Civic Tech",
   "NonTechnical":"Wellness & Stress Management, Resume & Cover Letters, Social Issues in the Tech Industry, Starting diversity groups at work",
   "Preferred":"Slack",
   "Slack":"@tommasina",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"In Person at Turing, Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays, after 5PM, Weekends, PM"
},
{
   "Timestamp":"1/24/2017 13:17:11",
   "Name":"Torie Joy-Warren",
   "Location":"Seattle, WA",
   "JobTitle":"Software Engineer",
   "Employer":"CareZone",
   "Background":"1508 Alumni. Previously worked in economic research.",
   "Technical":"Ruby/Rails, Technical Interview Prep",
   "NonTechnical":"Wellness & Stress Management, Technical Interview Prep, Social Issues in the Tech Industry",
   "Preferred":"Slack or Email",
   "Slack":"@torie",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM, Weekends, AM"
},
{
   "Timestamp":"9/18/2016 21:46:16",
   "Name":"Troy Denkinger",
   "Location":"Brooklyn, NY",
   "JobTitle":"VP Engineering",
   "Employer":"TuneCore, Inc.",
   "Background":"I've been coding for over 20 years and have a lot of experience in the digital music industry. For the past 10 years or so I have been an engineering manager at various startups and established companies.",
   "Technical":"Ruby/Rails, Functional Programming, Technical Interview Prep",
   "NonTechnical":"Project Management, Technical Interview Prep, Product management",
   "Preferred":"Slack or Email",
   "Slack":"",
   "Email":"",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Weekdays,  Lunchtime, Weekdays, after 5PM"
},
{
   "Timestamp":"5/2/2017 20:52:11",
   "Name":"Ville-Matti Hakanpää",
   "Location":"Raumna, Finland",
   "JobTitle":"Senior Software Developer",
   "Employer":"",
   "Background":"Over 15 years on the field. I live in Finland, have 4 kids and been programming my whole life. Fell in love with Javascript again after AngularJS appeared, now all my projects are build with React.\r\rI have relatively strong backgroun in PHP, but if I can, I do backend with Node. Been working with databases for a long time...and loving every minute of it.\r\rI do a lot...coach floorball for kids, build own projects...and sing! :)",
   "Technical":"node.js, React.js, Angular, CSS/Sass",
   "NonTechnical":"Project Management, Parenting",
   "Preferred":"Email",
   "Slack":"",
   "Email":"villematti@dapper.fi",
   "Phone":"",
   "PreferredLocation":"Screenhero, Zoom, Google Hangouts",
   "Availability":"Timezone is GMT +2, and then Weekdays after 5pm and weekends"
}
]

export default MENTORS;
